export { WebRTCStore, DEFAULT_RELAYS } from './store.js';
export { Peer } from './peer.js';
export {
  PeerId,
  generateUuid,
  MAX_HTL,
  MSG_TYPE_REQUEST,
  MSG_TYPE_RESPONSE,
  FRAGMENT_SIZE,
  type SignalingMessage,
  type WebRTCStoreConfig,
  type PeerStatus,
  type WebRTCStoreEvent,
  type WebRTCStoreEventHandler,
  type EventSigner,
  type EventEncrypter,
  type EventDecrypter,
  type GiftWrapper,
  type GiftUnwrapper,
  type SignedEvent,
  type PeerPool,
  type PeerClassifier,
  type PoolConfig,
  type WebRTCStats,
  type BandwidthSample,
  type DataRequest,
  type DataResponse,
} from './types.js';

// Protocol functions
export {
  encodeRequest,
  encodeResponse,
  parseMessage,
  createRequest,
  createResponse,
  createFragmentResponse,
  hashToKey,
  verifyHash,
  generatePeerHTLConfig,
  decrementHTL,
  shouldForward,
  type PeerHTLConfig,
  type PendingRequest,
} from './protocol.js';
